#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2026.2.1"

# Which optional robotpy components should be installed?
# -> equivalent to `pip install robotpy[extra1, ...]
components = [
    "apriltag",
    "commands2"
]

# Other pip packages to install, such as vendor packages (each element
# is equivalent to a line in requirements.txt)
requires = [
    "phoenix6",
    "robotpy-pathplannerlib",
    "robotpy-rev",
    "photonlibpy==2026.1.1rc4"
]

# Enables Isolated Test Mode
[tool.robotpy.pyfrc]
isolated = true